//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        project1.ServiceReference1.LoginResponse Login(project1.ServiceReference1.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<project1.ServiceReference1.LoginResponse> LoginAsync(project1.ServiceReference1.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name newUser from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        project1.ServiceReference1.RegisterResponse Register(project1.ServiceReference1.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<project1.ServiceReference1.RegisterResponse> RegisterAsync(project1.ServiceReference1.RegisterRequest request);
        
        // CODEGEN: Generating message contract since element name userToEdit from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserDetails", ReplyAction="*")]
        project1.ServiceReference1.UpdateUserDetailsResponse UpdateUserDetails(project1.ServiceReference1.UpdateUserDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<project1.ServiceReference1.UpdateUserDetailsResponse> UpdateUserDetailsAsync(project1.ServiceReference1.UpdateUserDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewUserDetails", ReplyAction="*")]
        project1.ServiceReference1.ViewUserDetailsResponse ViewUserDetails(project1.ServiceReference1.ViewUserDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewUserDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<project1.ServiceReference1.ViewUserDetailsResponse> ViewUserDetailsAsync(project1.ServiceReference1.ViewUserDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name getUserNameResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserName", ReplyAction="*")]
        project1.ServiceReference1.getUserNameResponse getUserName(project1.ServiceReference1.getUserNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserName", ReplyAction="*")]
        System.Threading.Tasks.Task<project1.ServiceReference1.getUserNameResponse> getUserNameAsync(project1.ServiceReference1.getUserNameRequest request);
        
        // CODEGEN: Generating message contract since element name authorized from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/paywithcredit", ReplyAction="*")]
        project1.ServiceReference1.paywithcreditResponse paywithcredit(project1.ServiceReference1.paywithcreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/paywithcredit", ReplyAction="*")]
        System.Threading.Tasks.Task<project1.ServiceReference1.paywithcreditResponse> paywithcreditAsync(project1.ServiceReference1.paywithcreditRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public project1.ServiceReference1.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(project1.ServiceReference1.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public project1.ServiceReference1.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(project1.ServiceReference1.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(System.Guid LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public project1.ServiceReference1.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(project1.ServiceReference1.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public project1.ServiceReference1.User newUser;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(project1.ServiceReference1.User newUser) {
            this.newUser = newUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public project1.ServiceReference1.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(project1.ServiceReference1.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(bool RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserDetails", Namespace="http://tempuri.org/", Order=0)]
        public project1.ServiceReference1.UpdateUserDetailsRequestBody Body;
        
        public UpdateUserDetailsRequest() {
        }
        
        public UpdateUserDetailsRequest(project1.ServiceReference1.UpdateUserDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public project1.ServiceReference1.User userToEdit;
        
        public UpdateUserDetailsRequestBody() {
        }
        
        public UpdateUserDetailsRequestBody(project1.ServiceReference1.User userToEdit) {
            this.userToEdit = userToEdit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public project1.ServiceReference1.UpdateUserDetailsResponseBody Body;
        
        public UpdateUserDetailsResponse() {
        }
        
        public UpdateUserDetailsResponse(project1.ServiceReference1.UpdateUserDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateUserDetailsResult;
        
        public UpdateUserDetailsResponseBody() {
        }
        
        public UpdateUserDetailsResponseBody(bool UpdateUserDetailsResult) {
            this.UpdateUserDetailsResult = UpdateUserDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewUserDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewUserDetails", Namespace="http://tempuri.org/", Order=0)]
        public project1.ServiceReference1.ViewUserDetailsRequestBody Body;
        
        public ViewUserDetailsRequest() {
        }
        
        public ViewUserDetailsRequest(project1.ServiceReference1.ViewUserDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ViewUserDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public ViewUserDetailsRequestBody() {
        }
        
        public ViewUserDetailsRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewUserDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewUserDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public project1.ServiceReference1.ViewUserDetailsResponseBody Body;
        
        public ViewUserDetailsResponse() {
        }
        
        public ViewUserDetailsResponse(project1.ServiceReference1.ViewUserDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ViewUserDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public project1.ServiceReference1.User ViewUserDetailsResult;
        
        public ViewUserDetailsResponseBody() {
        }
        
        public ViewUserDetailsResponseBody(project1.ServiceReference1.User ViewUserDetailsResult) {
            this.ViewUserDetailsResult = ViewUserDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserName", Namespace="http://tempuri.org/", Order=0)]
        public project1.ServiceReference1.getUserNameRequestBody Body;
        
        public getUserNameRequest() {
        }
        
        public getUserNameRequest(project1.ServiceReference1.getUserNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid userid;
        
        public getUserNameRequestBody() {
        }
        
        public getUserNameRequestBody(System.Guid userid) {
            this.userid = userid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public project1.ServiceReference1.getUserNameResponseBody Body;
        
        public getUserNameResponse() {
        }
        
        public getUserNameResponse(project1.ServiceReference1.getUserNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUserNameResult;
        
        public getUserNameResponseBody() {
        }
        
        public getUserNameResponseBody(string getUserNameResult) {
            this.getUserNameResult = getUserNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class paywithcreditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="paywithcredit", Namespace="http://tempuri.org/", Order=0)]
        public project1.ServiceReference1.paywithcreditRequestBody Body;
        
        public paywithcreditRequest() {
        }
        
        public paywithcreditRequest(project1.ServiceReference1.paywithcreditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class paywithcreditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authorized;
        
        public paywithcreditRequestBody() {
        }
        
        public paywithcreditRequestBody(string authorized) {
            this.authorized = authorized;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class paywithcreditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="paywithcreditResponse", Namespace="http://tempuri.org/", Order=0)]
        public project1.ServiceReference1.paywithcreditResponseBody Body;
        
        public paywithcreditResponse() {
        }
        
        public paywithcreditResponse(project1.ServiceReference1.paywithcreditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class paywithcreditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool paywithcreditResult;
        
        public paywithcreditResponseBody() {
        }
        
        public paywithcreditResponseBody(bool paywithcreditResult) {
            this.paywithcreditResult = paywithcreditResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : project1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<project1.ServiceReference1.WebService1Soap>, project1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        project1.ServiceReference1.LoginResponse project1.ServiceReference1.WebService1Soap.Login(project1.ServiceReference1.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public System.Guid Login(string userName, string password) {
            project1.ServiceReference1.LoginRequest inValue = new project1.ServiceReference1.LoginRequest();
            inValue.Body = new project1.ServiceReference1.LoginRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            project1.ServiceReference1.LoginResponse retVal = ((project1.ServiceReference1.WebService1Soap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<project1.ServiceReference1.LoginResponse> project1.ServiceReference1.WebService1Soap.LoginAsync(project1.ServiceReference1.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<project1.ServiceReference1.LoginResponse> LoginAsync(string userName, string password) {
            project1.ServiceReference1.LoginRequest inValue = new project1.ServiceReference1.LoginRequest();
            inValue.Body = new project1.ServiceReference1.LoginRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((project1.ServiceReference1.WebService1Soap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        project1.ServiceReference1.RegisterResponse project1.ServiceReference1.WebService1Soap.Register(project1.ServiceReference1.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public bool Register(project1.ServiceReference1.User newUser) {
            project1.ServiceReference1.RegisterRequest inValue = new project1.ServiceReference1.RegisterRequest();
            inValue.Body = new project1.ServiceReference1.RegisterRequestBody();
            inValue.Body.newUser = newUser;
            project1.ServiceReference1.RegisterResponse retVal = ((project1.ServiceReference1.WebService1Soap)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<project1.ServiceReference1.RegisterResponse> project1.ServiceReference1.WebService1Soap.RegisterAsync(project1.ServiceReference1.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<project1.ServiceReference1.RegisterResponse> RegisterAsync(project1.ServiceReference1.User newUser) {
            project1.ServiceReference1.RegisterRequest inValue = new project1.ServiceReference1.RegisterRequest();
            inValue.Body = new project1.ServiceReference1.RegisterRequestBody();
            inValue.Body.newUser = newUser;
            return ((project1.ServiceReference1.WebService1Soap)(this)).RegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        project1.ServiceReference1.UpdateUserDetailsResponse project1.ServiceReference1.WebService1Soap.UpdateUserDetails(project1.ServiceReference1.UpdateUserDetailsRequest request) {
            return base.Channel.UpdateUserDetails(request);
        }
        
        public bool UpdateUserDetails(project1.ServiceReference1.User userToEdit) {
            project1.ServiceReference1.UpdateUserDetailsRequest inValue = new project1.ServiceReference1.UpdateUserDetailsRequest();
            inValue.Body = new project1.ServiceReference1.UpdateUserDetailsRequestBody();
            inValue.Body.userToEdit = userToEdit;
            project1.ServiceReference1.UpdateUserDetailsResponse retVal = ((project1.ServiceReference1.WebService1Soap)(this)).UpdateUserDetails(inValue);
            return retVal.Body.UpdateUserDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<project1.ServiceReference1.UpdateUserDetailsResponse> project1.ServiceReference1.WebService1Soap.UpdateUserDetailsAsync(project1.ServiceReference1.UpdateUserDetailsRequest request) {
            return base.Channel.UpdateUserDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<project1.ServiceReference1.UpdateUserDetailsResponse> UpdateUserDetailsAsync(project1.ServiceReference1.User userToEdit) {
            project1.ServiceReference1.UpdateUserDetailsRequest inValue = new project1.ServiceReference1.UpdateUserDetailsRequest();
            inValue.Body = new project1.ServiceReference1.UpdateUserDetailsRequestBody();
            inValue.Body.userToEdit = userToEdit;
            return ((project1.ServiceReference1.WebService1Soap)(this)).UpdateUserDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        project1.ServiceReference1.ViewUserDetailsResponse project1.ServiceReference1.WebService1Soap.ViewUserDetails(project1.ServiceReference1.ViewUserDetailsRequest request) {
            return base.Channel.ViewUserDetails(request);
        }
        
        public project1.ServiceReference1.User ViewUserDetails(string userName) {
            project1.ServiceReference1.ViewUserDetailsRequest inValue = new project1.ServiceReference1.ViewUserDetailsRequest();
            inValue.Body = new project1.ServiceReference1.ViewUserDetailsRequestBody();
            inValue.Body.userName = userName;
            project1.ServiceReference1.ViewUserDetailsResponse retVal = ((project1.ServiceReference1.WebService1Soap)(this)).ViewUserDetails(inValue);
            return retVal.Body.ViewUserDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<project1.ServiceReference1.ViewUserDetailsResponse> project1.ServiceReference1.WebService1Soap.ViewUserDetailsAsync(project1.ServiceReference1.ViewUserDetailsRequest request) {
            return base.Channel.ViewUserDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<project1.ServiceReference1.ViewUserDetailsResponse> ViewUserDetailsAsync(string userName) {
            project1.ServiceReference1.ViewUserDetailsRequest inValue = new project1.ServiceReference1.ViewUserDetailsRequest();
            inValue.Body = new project1.ServiceReference1.ViewUserDetailsRequestBody();
            inValue.Body.userName = userName;
            return ((project1.ServiceReference1.WebService1Soap)(this)).ViewUserDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        project1.ServiceReference1.getUserNameResponse project1.ServiceReference1.WebService1Soap.getUserName(project1.ServiceReference1.getUserNameRequest request) {
            return base.Channel.getUserName(request);
        }
        
        public string getUserName(System.Guid userid) {
            project1.ServiceReference1.getUserNameRequest inValue = new project1.ServiceReference1.getUserNameRequest();
            inValue.Body = new project1.ServiceReference1.getUserNameRequestBody();
            inValue.Body.userid = userid;
            project1.ServiceReference1.getUserNameResponse retVal = ((project1.ServiceReference1.WebService1Soap)(this)).getUserName(inValue);
            return retVal.Body.getUserNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<project1.ServiceReference1.getUserNameResponse> project1.ServiceReference1.WebService1Soap.getUserNameAsync(project1.ServiceReference1.getUserNameRequest request) {
            return base.Channel.getUserNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<project1.ServiceReference1.getUserNameResponse> getUserNameAsync(System.Guid userid) {
            project1.ServiceReference1.getUserNameRequest inValue = new project1.ServiceReference1.getUserNameRequest();
            inValue.Body = new project1.ServiceReference1.getUserNameRequestBody();
            inValue.Body.userid = userid;
            return ((project1.ServiceReference1.WebService1Soap)(this)).getUserNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        project1.ServiceReference1.paywithcreditResponse project1.ServiceReference1.WebService1Soap.paywithcredit(project1.ServiceReference1.paywithcreditRequest request) {
            return base.Channel.paywithcredit(request);
        }
        
        public bool paywithcredit(string authorized) {
            project1.ServiceReference1.paywithcreditRequest inValue = new project1.ServiceReference1.paywithcreditRequest();
            inValue.Body = new project1.ServiceReference1.paywithcreditRequestBody();
            inValue.Body.authorized = authorized;
            project1.ServiceReference1.paywithcreditResponse retVal = ((project1.ServiceReference1.WebService1Soap)(this)).paywithcredit(inValue);
            return retVal.Body.paywithcreditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<project1.ServiceReference1.paywithcreditResponse> project1.ServiceReference1.WebService1Soap.paywithcreditAsync(project1.ServiceReference1.paywithcreditRequest request) {
            return base.Channel.paywithcreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<project1.ServiceReference1.paywithcreditResponse> paywithcreditAsync(string authorized) {
            project1.ServiceReference1.paywithcreditRequest inValue = new project1.ServiceReference1.paywithcreditRequest();
            inValue.Body = new project1.ServiceReference1.paywithcreditRequestBody();
            inValue.Body.authorized = authorized;
            return ((project1.ServiceReference1.WebService1Soap)(this)).paywithcreditAsync(inValue);
        }
    }
}
